# docker-compose.yml 用於定義和管理多個 Docker 容器服務的配置。
# 使用 'docker compose up' 可以根據此文件啟動所有定義的服務。

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

# services is all container I want to build in this group
services: # 定義所有要運行的服務（容器）
  # 前端服務 - React 應用
  aiot-frontend:
    logging: *default-logging # 使用預設的日誌配置
    build:
      # the context property is specifies the folder I want to use, like the command COPY and ADD in dockerfile are based on this context folder
      context: ../../AIOT/fe
      dockerfile: ./Dockerfile.fe # 指定 Dockerfile 路徑
    container_name: AIOT-fe # 指定容器名稱
    ports:
      - "3000:3000" # 將主機的 3000 端口映射到容器的 3000 端口
    # environment means the environment variables
    environment:
    # the option of NODE_ENV has production and development,
    # the production one would optimize and cancel the debug log
    # and the development one would keep the debug log and enable the hot reload
      - NODE_ENV=development # 設定環境變數為開發環境

    # since the docker compose, the fe container would auto recognize the be container's name, like aiot-backend
    # so in the react project, I just need to set the url like http://aiot-backend:8000/api

    # depend_on is the property that specifies the which container should be started before this container
    depends_on:
      - aiot-backend
    networks:
      - aiot-compose-network # 指定使用的網路
    volumes:
      - ../../AIOT/fe:/app # 將本地 frontend 資料夾掛載到容器 /app
      - /app/node_modules # 保持 node_modules 不被本地覆蓋
    restart: unless-stopped # 當容器異常停止時自動重啟

  # 後端服務 - Express.js API
  aiot-backend:
    logging: *default-logging # 使用預設的日誌配置
    build:
      context: ../../AIOT/be # 指定 Dockerfile 構建上下文目錄
      dockerfile: ./Dockerfile.be # 指定 Dockerfile 路徑

    container_name: AIOT-be # 指定容器名稱
    ports:
      - "8000:8000" # 將主機的 8000 端口映射到容器的 8000 端口
    environment:
      - NODE_ENV=development # 設定環境變數為開發環境
      - DATABASE_URL=mysql://admin:admin@aiot-mysqldb:3306/main_db # MySQL 資料庫連線字串
      - MONGODB_URL=mongodb://admin:admin@aiot-mongodb:27017/main_db?authSource=admin # MongoDB 連線字串
    depends_on:
      aiot-mysqldb:  # 啟動後端前需先啟動 MySQL
       condition: service_healthy # 確保 MySQL 健康檢查通過
      aiot-mongodb: # 啟動後端前需先啟動 MongoDB
       condition: service_healthy # 確保 MongoDB 健康檢查通過
    networks:
      - aiot-compose-network
    volumes:
      - ../../AIOT/be:/app # 將本地 backend 資料夾掛載到容器 /app
      - /app/node_modules # 保持 node_modules 不被本地覆蓋
    restart: unless-stopped # 當容器異常停止時自動重啟

  # SQL 資料庫服務 - MySQL
  aiot-mysqldb:
    logging: *default-logging # 使用預設的日誌配置
    image: mysql:latest # using the latest official mysql image
    container_name: AIOT-mysqldb # 指定容器名稱
    environment:
      - MYSQL_USER=admin # 新增的使用者名稱
      - MYSQL_ROOT_PASSWORD=admin # MySQL root 使用者密碼
      - MYSQL_DATABASE=main_db # 預設建立的資料庫名稱
      - MYSQL_PASSWORD=admin # 新增使用者的密碼
      - TZ=Asia/Taipei # 設定時區為台北
    volumes:
      - mysql_data:/var/lib/mysql # 使用 volume 儲存 MySQL 資料
    networks:
      - aiot-compose-network # 指定使用的網路
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped # 異常停止時自動重啟

  # NoSQL 資料庫服務 - MongoDB
  aiot-mongodb:
    logging: *default-logging # 使用預設的日誌配置
    image: mongo:latest # using the latest official mongo image
    container_name: AIOT-mongodb # 指定容器名稱
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin # MongoDB root 使用者名稱
      - MONGO_INITDB_ROOT_PASSWORD=admin # root 使用者密碼
      - MONGO_INITDB_DATABASE=main_db # 預設建立的資料庫名稱
    volumes:
      - mongodb_data:/data/db # 使用 volume 儲存 MongoDB 資料
    networks:
      - aiot-compose-network # 指定使用的網路
    healthcheck:
      test: ["CMD", "mongosh", "-u", "admin", "-p", "admin", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped # 異常停止時自動重啟

# 定義持久化資料的 volumes
volumes:
  mysql_data:
  # the local in this property means store the data with volume format in local device but not with format of mysqldata or mongodbdata
  # so I do not need to set the relative config of mysql or mongodb in the local device, because I build these containers to handle these
  # the docker will make these containers to access the volume which stored in the local device to be the db data
    driver: local
  mongodb_data:
    driver: local

# the networks section is how the containers communicate with each other in this same group, and which need to be defined by myself
networks:
  # here is the tailored name designed by myself for the network
  aiot-compose-network:
  # in this context, the driver means the type of network, not the general meaning of driver as I know
  # for local device development, using the bridge network is the appropriate choice
  # another choice is host, but which is used for share the device's network stack
    driver: bridge # 使用 bridge 網路模式


# appendix:
#  the volume is a mechanism, not a type of container; and which store the data or any file outside the container permanently